#!/usr/bin/env bash
# =============================================================================
# sync-env.sh — generate per-repo env files from the single source of truth.
#
# The canonical files (env/local.env, env/prod.env) live in this repo and are
# sectioned by target ([backend], [web], [maestro]). This script extracts each
# section into the env file that repo expects:
#
#   ./scripts/sync-env.sh            # local  -> local.env
#   ./scripts/sync-env.sh --prod     # prod   -> prod.env
#
# Outputs (relative to repo roots):
#   backend  -> ./.env
#   web      -> ../audiobookphile-web/.env.local
#   app      -> ../audiobookphile-app/.maestro/.env
#
# Merge semantics: non-blank canonical values always win. Blank canonical
# values (secrets) preserve whatever is already set in the target file, so
# locally-filled secrets (Supabase CLI token, Maestro test creds) survive
# re-syncs. Secrets are not stored in env/*.env — configure them in Vercel /
# Supabase Vault / Edge Function secrets instead.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="local"
if [[ "${1:-}" == "--prod" ]]; then
  MODE="prod"
elif [[ -n "${1:-}" ]]; then
  echo "usage: $0 [--prod]" >&2
  exit 1
fi

SOURCE="$ROOT/env/$MODE.env"
[[ -f "$SOURCE" ]] || { echo "error: source not found: $SOURCE" >&2; exit 1; }

# resolve_side <rel> — find a sibling repo dir
resolve_side() {
  local rel="$1"
  local d="$ROOT/../$rel"
  [[ -d "$d" ]] || { echo "error: sibling repo not found: $d" >&2; exit 1; }
  echo "$d"
}

WEB_DIR="$(resolve_side audiobookphile-web)"
APP_DIR="$(resolve_side audiobookphile-app)"

# extract_section <section> -> prints that section's KEY=VALUE lines
extract_section() {
  local section="$1" in_section=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^\#\ \[([a-z]+)\] ]]; then
      if [[ "${BASH_REMATCH[1]}" == "$section" ]]; then
        in_section=1
      else
        in_section=0
      fi
      continue
    fi
    if [[ "$in_section" == "1" && "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
      printf '%s\n' "$line"
    fi
  done < "$SOURCE"
}

write_target() {
  local target="$1" section="$2" tmp key value existing
  tmp="$(mktemp)"
  {
    printf '# Generated by audiobookphile-backend/scripts/sync-env.sh (%s) — DO NOT EDIT. Edit backend/env/%s.env instead.\n' "$MODE" "$MODE"
    while IFS='=' read -r key value; do
      if [[ -z "$value" && -f "$target" ]]; then
        existing="$(grep -E "^${key}=" "$target" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
        if [[ -n "$existing" ]]; then
          printf '%s=%s\n' "$key" "$existing"
          continue
        fi
      fi
      printf '%s=%s\n' "$key" "$value"
    done < <(extract_section "$section")
  } > "$tmp"
  mv "$tmp" "$target"
  echo "  wrote $target"
}

echo "Syncing [$MODE] from $SOURCE"
mkdir -p "$APP_DIR/.maestro"
write_target "$ROOT/.env" "backend"
write_target "$WEB_DIR/.env.local" "web"
write_target "$APP_DIR/.maestro/.env" "maestro"
echo "Done."
