#!/usr/bin/env bash
# =============================================================================
# sync-env.sh — generate per-repo env files from the single source of truth.
#
# The canonical file (env/local.env) lives in this repo and is sectioned by
# target ([backend], [web], [maestro]). This script extracts each section into
# the env file that repo expects:
#
#   ./scripts/sync-env.sh
#
# Outputs (relative to repo roots):
#   backend  -> ./.env
#   web      -> ../audiobookphile-web/.env.local
#   app      -> ../audiobookphile-app/.maestro/.env
#
# Merge semantics: non-blank canonical values always win. Blank canonical
# values (secrets) preserve whatever is already set in the target file, so
# locally-filled secrets (Supabase CLI token, Maestro test creds) survive
# re-syncs. Secrets are not stored in env/local.env — configure them in
# Vercel / Supabase Vault / Edge Function secrets instead. Production values
# live on the platforms, not in this repo.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

SOURCE="$ROOT/env/local.env"
[[ -f "$SOURCE" ]] || { echo "error: source not found: $SOURCE" >&2; exit 1; }

# resolve_side <rel> — find a sibling repo dir
resolve_side() {
  local rel="$1"
  local d="$ROOT/../$rel"
  [[ -d "$d" ]] || { echo "error: sibling repo not found: $d" >&2; exit 1; }
  echo "$d"
}

WEB_DIR="$(resolve_side audiobookphile-web)"
APP_DIR="$(resolve_side audiobookphile-app)"

# extract_section <section> -> prints that section's KEY=VALUE lines
extract_section() {
  local section="$1" in_section=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^\#\ \[([a-z]+)\] ]]; then
      if [[ "${BASH_REMATCH[1]}" == "$section" ]]; then
        in_section=1
      else
        in_section=0
      fi
      continue
    fi
    if [[ "$in_section" == "1" && "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
      printf '%s\n' "$line"
    fi
  done < "$SOURCE"
}

write_target() {
  local target="$1" section="$2" tmp key value existing
  tmp="$(mktemp)"
  {
    printf '# Generated by audiobookphile-backend/scripts/sync-env.sh — DO NOT EDIT. Edit backend/env/local.env instead.\n'
    while IFS='=' read -r key value; do
      if [[ -z "$value" && -f "$target" ]]; then
        existing="$(grep -E "^${key}=" "$target" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
        if [[ -n "$existing" ]]; then
          printf '%s=%s\n' "$key" "$existing"
          continue
        fi
      fi
      printf '%s=%s\n' "$key" "$value"
    done < <(extract_section "$section")
  } > "$tmp"
  mv "$tmp" "$target"
  echo "  wrote $target"
}

# Maestro credential subflow: Maestro 2.8's bare ${ENV_VAR} interpolation in
# inputText mangles any value containing ':' or '/' (types the literal
# "undefined"), so flows consume credentials as evalScript output variables
# instead. This file is gitignored — never commit it.
write_maestro_credentials() {
  local target="$APP_DIR/.maestro/flows/_credentials.yaml" server email password
  server="$(extract_section "maestro" | grep -E '^SERVER_URL=' | cut -d= -f2-)"
  # Email/password are local secrets: the canonical [maestro] section leaves
  # them blank and sync-env preserves them in .maestro/.env — read from there.
  email="$(grep -E '^TEST_EMAIL=' "$APP_DIR/.maestro/.env" 2>/dev/null | cut -d= -f2-)"
  password="$(grep -E '^TEST_PASSWORD=' "$APP_DIR/.maestro/.env" 2>/dev/null | cut -d= -f2-)"
  if [[ -z "$email" ]]; then
    echo "  (no TEST_EMAIL in [maestro] — _credentials.yaml left as-is)"
    return 0
  fi
  {
    printf '%s\n' \
      "# Generated by audiobookphile-backend/scripts/sync-env.sh — DO NOT EDIT and" \
      "# DO NOT COMMIT (gitignored). Credentials for the e2e flows as Maestro" \
      '# output variables: bare ${ENV_VAR} interpolation in inputText mangles' \
      "# values containing ':' or '/', while evalScript values pass through verbatim." \
      "appId: club.foodshare.audiobookphile" \
      "name: e2e credentials" \
      "---"
    printf -- "- evalScript: \${output.server = '%s'; output.email = '%s'; output.password = '%s'}\n" \
      "$server" "$email" "$password"
  } > "$target"
  echo "  wrote $target"
}

echo "Syncing from $SOURCE"
mkdir -p "$APP_DIR/.maestro"
write_target "$ROOT/.env" "backend"
write_target "$WEB_DIR/.env.local" "web"
write_target "$APP_DIR/.maestro/.env" "maestro"
write_maestro_credentials
echo "Done."
